"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { FileText, Link2, Pencil, Plus, Search, Trash2, UserMinus, Users } from "lucide-react";
import { toast } from "sonner";
import { WorkspaceShell } from "@/components/workspace/shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { changeGroupRole, createGroupInviteLink, createWorkspaceFile, deleteWorkspaceFile, disbandGroup, getGroup, Group, GroupMember, inviteGroupUser, leaveGroup, listGroupMembers, listWorkspaceFiles, removeGroupMember, renameGroup, searchUsers, UserSearchResult, WorkspaceFile } from "@/lib/api/client";

type Confirm = { kind: "disband" | "leave" | "member" | "file"; id?: string; label: string };
const roleLabels = { owner: "所有者", admin: "管理员", member: "成员" } as const;

export default function GroupDetailPage() {
  const { groupId } = useParams<{ groupId: string }>(); const router = useRouter();
  const [group, setGroup] = useState<Group | null>(null); const [members, setMembers] = useState<GroupMember[]>([]); const [files, setFiles] = useState<WorkspaceFile[]>([]);
  const [confirm, setConfirm] = useState<Confirm | null>(null); const [renameOpen, setRenameOpen] = useState(false); const [inviteOpen, setInviteOpen] = useState(false); const [createOpen, setCreateOpen] = useState(false);
  const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [results, setResults] = useState<UserSearchResult[]>([]); const [type, setType] = useState<"mindmap" | "markdown">("mindmap");
  const load = useCallback(async () => { try { const [g, m, f] = await Promise.all([getGroup(groupId), listGroupMembers(groupId), listWorkspaceFiles(groupId)]); setGroup(g); setMembers(m.items); setFiles(f.items); } catch { toast.error("群组加载失败"); } }, [groupId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (query.trim().length < 1) return; let active = true; const timer = window.setTimeout(() => searchUsers(query).then((v) => { if (active) setResults(v.items); }).catch(() => { if (active) setResults([]); }), 250); return () => { active = false; window.clearTimeout(timer); }; }, [query]);
  if (!group) return <WorkspaceShell><div className="py-20 text-center text-sm text-muted-foreground">正在加载群组...</div></WorkspaceShell>;
  const canInvite = group.role === "owner" || group.role === "admin";
  async function executeConfirm() { if (!confirm) return; try { if (confirm.kind === "disband") { await disbandGroup(groupId); router.push("/workspace/groups"); } else if (confirm.kind === "leave") { await leaveGroup(groupId); router.push("/workspace/groups"); } else if (confirm.kind === "member" && confirm.id) { await removeGroupMember(groupId, confirm.id); await load(); } else if (confirm.kind === "file" && confirm.id) { await deleteWorkspaceFile(groupId, confirm.id); await load(); } setConfirm(null); toast.success("操作已完成"); } catch { toast.error("操作失败"); } }
  async function updateName() { await renameGroup(groupId, name.trim()); setRenameOpen(false); await load(); }
  async function invite(user: UserSearchResult) { try { await inviteGroupUser(groupId, user.id); toast.success("邀请已发送"); setQuery(""); setResults([]); } catch { toast.error("用户已在群组中或邀请仍待处理"); } }
  async function share() { try { const value = await createGroupInviteLink(groupId); await navigator.clipboard.writeText(`${window.location.origin}${value.url}`); toast.success("一次性邀请链接已复制"); } catch { toast.error("链接生成失败"); } }
  async function createFile() { if (!name.trim()) return; await createWorkspaceFile(groupId, { name: name.trim(), type }); setName(""); setCreateOpen(false); await load(); }
  return <WorkspaceShell><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2"><Badge variant="outline">{roleLabels[group.role]}</Badge><Badge variant="secondary">{group.member_count} 位成员</Badge></div><h1 className="mt-3 text-2xl font-semibold">{group.name}</h1><p className="mt-2 text-sm text-muted-foreground">群组成员与共享文件空间</p></div><div className="flex flex-wrap gap-2">{canInvite && <><Button variant="outline" onClick={() => setInviteOpen(true)}><Users />邀请成员</Button><Button variant="outline" onClick={share}><Link2 />邀请链接</Button></>}{group.role === "owner" ? <><Button variant="outline" onClick={() => { setName(group.name); setRenameOpen(true); }}><Pencil />改名</Button><Button variant="destructive" onClick={() => setConfirm({ kind: "disband", label: group.name })}><Trash2 />解散</Button></> : <Button variant="destructive" onClick={() => setConfirm({ kind: "leave", label: group.name })}><UserMinus />退出群组</Button>}</div></div>
    <Tabs defaultValue="members"><TabsList><TabsTrigger value="members">成员管理</TabsTrigger><TabsTrigger value="files">群组文件</TabsTrigger></TabsList>
      <TabsContent value="members" className="pt-4"><div className="glass-surface overflow-hidden rounded-lg border">{members.map((member) => <div key={member.id} className="flex flex-wrap items-center gap-3 border-b border-white/10 p-4 last:border-0"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{member.display_name}</p><p className="text-xs text-muted-foreground">{member.email}</p></div>{group.role === "owner" && member.role !== "owner" ? <Select value={member.role} onValueChange={(value) => changeGroupRole(groupId, member.id, value as "admin" | "member").then(load)}><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="admin">管理员</SelectItem><SelectItem value="member">成员</SelectItem></SelectContent></Select> : <Badge variant="secondary">{roleLabels[member.role]}</Badge>}{member.role !== "owner" && ((group.role === "owner") || (group.role === "admin" && member.role === "member")) && <Button size="icon-sm" variant="ghost" aria-label={`移除 ${member.display_name}`} onClick={() => setConfirm({ kind: "member", id: member.id, label: member.display_name })}><UserMinus /></Button>}</div>)}</div></TabsContent>
      <TabsContent value="files" className="pt-4"><div className="mb-4 flex justify-end"><Button onClick={() => { setName(""); setCreateOpen(true); }}><Plus />新建文件</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{files.map((file) => <Card key={file.id} interactive className="relative p-4"><Link href={file.type === "mindmap" ? `/workspace/files/${file.id}?organization=${groupId}` : "#"} className="block"><FileText className="size-5 text-pink-200" /><h2 className="mt-4 truncate text-sm font-medium">{file.name}</h2><p className="mt-2 text-xs text-muted-foreground">{file.type}</p></Link><Button className="absolute right-3 top-3" size="icon-sm" variant="ghost" aria-label={`删除 ${file.name}`} onClick={() => setConfirm({ kind: "file", id: file.id, label: file.name })}><Trash2 /></Button></Card>)}</div></TabsContent>
    </Tabs>
    <Dialog open={renameOpen} onOpenChange={setRenameOpen}><DialogContent><DialogHeader><DialogTitle>修改群组名称</DialogTitle></DialogHeader><Input value={name} onChange={(e) => setName(e.target.value)} /><DialogFooter showCloseButton><Button onClick={updateName}>保存</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogContent><DialogHeader><DialogTitle>邀请成员</DialogTitle><DialogDescription>按姓名或邮箱查找已验证用户。</DialogDescription></DialogHeader><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="输入至少 1 个字符" /></div><div className="max-h-64 space-y-2 overflow-auto">{query.trim().length > 0 && results.map((user) => <button key={user.id} className="glass-surface flex w-full items-center justify-between rounded-md border p-3 text-left" onClick={() => invite(user)}><span><span className="block text-sm">{user.display_name}</span><span className="text-xs text-muted-foreground">{user.email}</span></span><Plus className="size-4" /></button>)}</div></DialogContent></Dialog>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>新建群组文件</DialogTitle></DialogHeader><div className="grid gap-2"><Label>文件名称</Label><Input value={name} onChange={(e) => setName(e.target.value)} /></div><Select value={type} onValueChange={(v) => setType(v as "mindmap" | "markdown")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="mindmap">Mindmap</SelectItem><SelectItem value="markdown">Markdown</SelectItem></SelectContent></Select><DialogFooter showCloseButton><Button onClick={createFile}>创建</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(confirm)} onOpenChange={(open) => !open && setConfirm(null)}><DialogContent><DialogHeader><DialogTitle>确认此操作？</DialogTitle><DialogDescription>你即将处理“{confirm?.label}”。此操作可能无法恢复。</DialogDescription></DialogHeader><DialogFooter showCloseButton><Button variant="destructive" onClick={executeConfirm}>确认</Button></DialogFooter></DialogContent></Dialog>
  </WorkspaceShell>;
}
